server:
  port: 8885
spring:
  application:
    name: serverconfig
  #git 远程仓库相关配置 若是私有项目 需要用户名密码
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CSY9257/springcloud-sjgc.git
          username: CSY9257
          password: Shuangyin21
          #配置文件所在的文件夹(必须是文件所在的文件夹 不能是父文件夹)
          search-paths: config-server/feign
eureka:
  client:
    service-url:
      #当前生产者注册地址 （注册中心地址）
      defaultZone: http://localhost:8888/eureka
