server:
  port: 8881

spring:
  application:
    name: service-config
  kafka:
    consumer:
      enable-auto-commit: true  #指定消息被消费之后自动提交偏移量（即消息的编号，表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的编号，以便于下次继续消费）。
      group-id: applog  #消费者组
      auto-offset-reset: latest    #从最近的地方开始消费
      bootstrap-servers: localhost:9092

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sjgc?useUnicode=true&characterEncoding=utf-8
    driver-class-name:  com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
      instance:
        instance-id: ${spring.application.name}:${server.port}

